# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpparma_hello_world <- function() {
    .Call(`_ExponentialGM_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_ExponentialGM_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_ExponentialGM_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_ExponentialGM_rcpparma_bothproducts`, x)
}

prob_kernel_cpp_pgm <- function(y, theta) {
    .Call(`_ExponentialGM_prob_kernel_cpp_pgm`, y, theta)
}

z_functions_cpp_pgm <- function(theta, N, phi) {
    .Call(`_ExponentialGM_z_functions_cpp_pgm`, theta, N, phi)
}

loglike_grad_cpp_pgm <- function(theta, X, N) {
    .Call(`_ExponentialGM_loglike_grad_cpp_pgm`, theta, X, N)
}

z_theta_cpp_pgm <- function(theta, N, phi) {
    .Call(`_ExponentialGM_z_theta_cpp_pgm`, theta, N, phi)
}

loglike_cpp_pgm <- function(theta, X, N) {
    .Call(`_ExponentialGM_loglike_cpp_pgm`, theta, X, N)
}

HMC_cpp_pgm <- function(U, grad_U, epsilon, L, current_q, matrix_A) {
    .Call(`_ExponentialGM_HMC_cpp_pgm`, U, grad_U, epsilon, L, current_q, matrix_A)
}

z_functions_cpp_ising <- function(theta, N, phi) {
    .Call(`_ExponentialGM_z_functions_cpp_ising`, theta, N, phi)
}

loglike_grad_cpp_ising <- function(theta, X, N) {
    .Call(`_ExponentialGM_loglike_grad_cpp_ising`, theta, X, N)
}

prob_kernel_cpp_ising <- function(y, theta) {
    .Call(`_ExponentialGM_prob_kernel_cpp_ising`, y, theta)
}

z_theta_cpp_ising <- function(theta, N, phi) {
    .Call(`_ExponentialGM_z_theta_cpp_ising`, theta, N, phi)
}

loglike_cpp_ising <- function(theta, X, N) {
    .Call(`_ExponentialGM_loglike_cpp_ising`, theta, X, N)
}

HMC_cpp_ising <- function(U, grad_U, epsilon, L, current_q) {
    .Call(`_ExponentialGM_HMC_cpp_ising`, U, grad_U, epsilon, L, current_q)
}

